# Generated by Django 4.2.2 on 2023-06-26 10:22

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='blogs')),
                ('slug', autoslug.fields.AutoSlugField()),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('category', models.CharField(choices=[('Politics', 'Politics'), ('Business', 'Business'), ('Corporate', 'Corporate'), ('Health', 'Health'), ('Science', 'Science'), ('Education', 'Education'), ('Foods', 'Foods'), ('Entertainment', 'Entertainment'), ('Lifestyle', 'Lifestyle')], max_length=50)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
