# Generated by Django 4.2.2 on 2023-06-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='article',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blog',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
