# Generated by Django 4.2 on 2025-03-04 11:30

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='article',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
