# Generated by Django 4.2 on 2025-06-14 13:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0007_blog_views_comment_blogview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogview',
            old_name='news',
            new_name='blog',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='news',
            new_name='blog',
        ),
        migrations.AlterUniqueTogether(
            name='blogview',
            unique_together={('blog', 'user')},
        ),
    ]
