# Generated by Django 4.2 on 2025-06-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_alter_blogview_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogview',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
